--
DROP TABLE IF EXISTS MEDICATION;

CREATE TABLE MEDICATION(
    ID VARCHAR PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    WEIGHT INT NOT NULL,
    CODE VARCHAR NOT NULL UNIQUE,
    IMAGE VARCHAR
);

INSERT INTO MEDICATION ("ID", "NAME", "WEIGHT", "CODE") VALUES ('AASDSADFFV', 'Aspirin', 100, 'A5H6_9B7D');
--INSERT INTO MEDICATION (id, name, weight, code) values ('AASDKKKSSD', 'Acetaminophen', 500, 'L2M9_N8R4');
